tag: ""
random_seed: 42

##############
# Dataloader #
##############
dataloader:
  dataset: "cifar10"
  num_workers: 1

#########
# Model #
#########
model:
  num_blocks: 1
  input_sequence_length: 64
  embedding_dim: 64
  expansion_factor: 1
  image_to_sequence:
    patch_size: 1

###########
# Trainer #
###########
trainer:
  # gpu, cpu
  device: "gpu"
  num_update_steps: 10000000
  batch_size: 64
  learning_rate: 6.0e-4
  weight_decay: 1.0e-5
  gradient_clipping:
    is_activated: false 
    max_norm: 1.0

load_model:
  is_activated: false 
  model_name: "cifar10"
  model_path: -1

########
# Data #
########
data:
  n_classes: Null
  input_shape: Null

###########
# Summary #
###########
summary:
  save_train_stats:
    every_n_updates: 1000
  save_test_stats:
    every_n_updates: 10000
  save_model:
    every_n_updates: 10000
  add_position_embeddings:
    every_n_updates: 10000
  add_token_embeddings:
    every_n_updates: 10000
  add_linear_weights:
    every_n_updates: 10000
  add_graph: false

###############
# Directories #
###############
dirs:
  data: "data"
  runs: "runs"
  weights: "weights"
